### ISSUE TITLE
100% coverage

### ISSUE THREAD

**Issue by UltCombo** [wearefractal/glob-stream#34]
This is the only line of code that is not covered yet: https://github.com/wearefractal/glob-stream/blob/1f26389f0408ed33201c17f4658b882242fde881/index.js#L105

The `return true` doesn't make much sense to me, should we throw an error instead? Then we can just add a test to cover that.

**Comment by UltCombo** [comment]
Or perhaps, `return false` if you'd prefer to fail silently. Though throwing would make more sense, IMO.

**Comment by contra** [comment]
Should throw on unknown glob type or invalid glob on construction of the stream
