### ISSUE TITLE
globs nothing when directory contains backets

### ISSUE THREAD

**Issue by vicary** [wearefractal/glob-stream#39]
Basically my `gulp.src('test/*.js')` returns nothing when my `process.cwd()` contains `[]` brackets.

Tracing down the `gulp` dependency tree:
```
├─┬ gulp@3.8.11
│ └─┬ vinyl-fs@0.3.13
│   ├─┬ glob-stream@3.1.18
│   │ ├─┬ glob@4.4.0
```

I explicitly installed those versions and here is my test scripts:
```Javascript
require('vinyl-fs')
  .src('test/*.js')
  .on('data', function() { console.log(arguments); }); // no output

require('glob-stream')
  .create('test/*.js')
  .on('data', function() { console.log(arguments); }); // no output

require('glob')('test/*.js', 
  function() { console.log(arguments); }); // lists out my files
```

Further testing shows that with the current version `glob-stream@4.0.1` the problem still occurs.

**Comment by heikki** [comment]
https://github.com/isaacs/minimatch/issues/50

**Comment by vicary** [comment]
Oh thanks, closing this.
